# Generated by Django 3.2.25 on 2024-03-28 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccerwiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='related_sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccerwiki.category'),
        ),
    ]
