# Generated by Django 3.2.25 on 2024-03-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccerwiki', '0002_league_related_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementdetails',
            old_name='user',
            new_name='player',
        ),
    ]
