# Generated by Django 3.2.25 on 2024-03-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerwiki', '0003_rename_user_achievementdetails_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdetails',
            name='age',
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
